twobuntu/articles/urls.py
from django.conf.urls import url

from twobuntu.articles import views


urlpatterns = [
    url(r'^(?P<id>\d+)/(?:(?P<slug>[\w-]+)/)?$', views.view, name='view'),

    url(r'^editor/(?:(?P<id>\d+)/)?$', views.editor, name='editor'),
    url(r'^(?P<action>submit|publish|release)/(?P<id>\d+)/$', views.modify, name='modify'),
    url(r'^schedule/(?P<id>\d+)/$', views.schedule, name='schedule'),
    url(r'^delete/(?P<id>\d+)/$', views.delete, name='delete'),

    url(r'^search/$', views.search, name='search'),
    url(r'^markdown/$', views.markdown, name='markdown'),
]

twobuntu/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap

from twobuntu import views
from twobuntu.feeds import LatestArticlesFeed
from twobuntu.sitemaps import HomePageSitemap, StaticViewSitemap


sitemaps = {
    'home': HomePageSitemap,
    'static': StaticViewSitemap,
}

urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^links/$', views.links, name='links'),
    url(r'^feedback/$', views.feedback, name='feedback'),
    url(r'^join/$', views.join, name='join'),
    url(r'^opensearch\.xml$', views.opensearch, name='opensearch'),

    url(r'^accounts/', include('twobuntu.accounts.urls', 'accounts')),
    url(r'^articles/', include('twobuntu.articles.urls', 'articles')),
    url(r'^api/', include('twobuntu.api.urls', 'api')),
    url(r'^categories/', include('twobuntu.categories.urls', 'categories')),
    url(r'^images/', include('twobuntu.images.urls', 'images')),
    url(r'^news/', include('twobuntu.news.urls', 'news')),
    url(r'^touch/', include('twobuntu.touch.urls', 'touch')),

    # Shortened URLs can redirect anywhere
    url(r'^(?P<key>[0-9a-f]{6})/', include('twobuntu.shorturls.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^rss/$', LatestArticlesFeed(), name='rss'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twobuntu/articles/models.py
from django.core.cache import cache
from django.contrib.auth.models import User
from django.db import models
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from django.utils.encoding import python_2_unicode_compatible
from django.utils.timezone import now

from twobuntu.categories.models import Category
from twobuntu.cmarkdown import cmarkdown
from twobuntu.images.models import Image


@python_2_unicode_compatible
class Article(models.Model):
    """
    A post written in Markdown by an author.
    """

    # Article status constants
    DRAFT = 0
    UNAPPROVED = 1
    PUBLISHED = 2

    STATUS = (
        (DRAFT, 'Draft'),
        (UNAPPROVED, 'Unapproved'),
        (PUBLISHED, 'Published'),
    )

    author = models.ForeignKey(
        User,
        help_text="The user writing the article.",
    )
    category = models.ForeignKey(
        Category,
        help_text="The category of the article.",
    )
    title = models.CharField(
        max_length=200,
        help_text="The title of the article.",
    )
    body = models.TextField(help_text="The body of the article [in Markdown].")
    image = models.ForeignKey(
        Image,
        blank=True,
        null=True,
        help_text="An image highlighting the contents of the article.",
    )
    status = models.PositiveSmallIntegerField(
        choices=STATUS,
        default=DRAFT,
        help_text="The current status of the article.",
    )
    cc_license = models.BooleanField(
        default=True,
        help_text="Whether the article is released under the CC-BY-SA 4.0 license or not.",
    )
    date = models.DateTimeField()

    def __str__(self):
        return '%s%s' % (
            self.title,
            ' [%s]' % self.get_status_display() if not self.status == self.PUBLISHED else '',
        )

    @models.permalink
    def get_absolute_url(self):
        kwargs, slug = {'id': self.id}, slugify(self.title)
        if slug:
            kwargs['slug'] = slug
        return ('articles:view', (), kwargs)

    def can_edit(self, request):
        """
        Determine if the article may be edited by the current user.
        """
        # The user must either be staff or have written the article and not published it yet
        return request.user.is_staff or request.user == self.author and self.status == self.DRAFT

    def can_view(self, request):
        """
        Determine if the article may be viewed by the current user.
        """
        # The user must either be staff or have written the article or it must be published
        return request.user.is_staff or request.user == self.author or self.status == self.PUBLISHED

    @property
    def markdown_key(self):
        """
        Return the key used for caching markdown.
        """
        return 'article-%d-markdown' % self.id

    def related(self):
        """
        Returns a QuerySet of related articles.
        """
        return Article.objects.filter(~models.Q(id=self.id), status=self.PUBLISHED, category=self.category)

    def render(self):
        """
        Render the Markdown body.
        """
        md = cache.get(self.markdown_key)
        if not md:
            md = cmarkdown(self.body)
            cache.set(self.markdown_key, md)
        return md

    @classmethod
    def apply_filter(cls, request, *args):
        """
        Return a QuerySet with the correct filter applied based on the request.
        """
        args = list(args)
        if not request.user.is_staff:
            args.append(models.Q(author=request.user.id) | models.Q(status=cls.PUBLISHED))
        return cls.objects.filter(*args)

    class Meta:
        ordering = ('status', '-date')


@receiver(models.signals.post_init, sender=Article)
def set_status(instance, **kwargs):
    """
    Store the status of the article before it is modified.
    """
    instance.old_status = instance.status


@receiver(models.signals.pre_save, sender=Article)
def update_date(instance, **kwargs):
    """
    Update the date if required.
    """
    if not instance.status == instance.old_status == Article.PUBLISHED:
        instance.date = now()


@python_2_unicode_compatible
class ScheduledArticle(models.Model):
    """
    An article to be published at a later date.
    """

    article = models.OneToOneField(
        Article,
        primary_key=True,
    )
    date = models.DateTimeField(help_text="Date/time to publish article (YYYY-MM-DD HH:MM:SS).")

    def __str__(self):
        return unicode(self.article)


@receiver(models.signals.post_save, sender=Article)
def clear_cache_and_remove_scheduled(instance, created, **kwargs):
    """
    Clear the cache and remove any scheduled articles instance.
    """
    if not created:
        cache.delete(instance.markdown_key)
    if instance.status == Article.PUBLISHED:
        ScheduledArticle.objects.filter(article=instance).delete()

twobuntu/articles/forms.py
from django import forms

from twobuntu.articles.models import Article, ScheduledArticle


class EditorForm(forms.ModelForm):
    """
    Form for entering or editing articles.
    """

    # The <textarea> needs this set so that the form can validate on the client
    # side without any content (due to ACE editor)
    use_required_attribute = False

    class Meta:
        model = Article
        fields = ('category', 'title', 'body')


class ScheduledArticleForm(forms.ModelForm):
    """
    Form for scheduling articles.
    """

    class Meta:
        model = ScheduledArticle
        fields = ('date',)


class DeleteArticleForm(forms.Form):
    """
    Form for deleting articles.
    """

    # Intentionally blank - submitting the form
    # is considered consent to delete the article.

twobuntu/articles/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.mail import mail_admins
from django.db import transaction
from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.views.decorators.http import require_POST

from twobuntu.articles.forms import DeleteArticleForm, EditorForm, ScheduledArticleForm
from twobuntu.articles.models import Article, ScheduledArticle
from twobuntu.decorators import canonical


@canonical(Article)
def view(request, article):
    """
    Display the specified article.
    """
    if not article.can_view(request):
        raise Http404
    return render(request, 'articles/view.html', {
        'title': article,
        'parent': {
            'title': article.category,
            'url': article.category.get_absolute_url(),
        },
        'article': article,
        'rendered': article.render(),
        'can_edit': article.can_edit(request),
        'social': (
            ('https://www.facebook.com/sharer.php?u=', 'Facebook', 'fa-facebook-square'),
            ('https://plus.google.com/share?url=', 'Google+', 'fa-google-plus-square'),
            ('https://twitter.com/share?url=', 'Twitter', 'fa-twitter-square'),
            ('http://tumblr.com/share?s=&v=3&u=', 'Tumblr', 'fa-tumblr-square'),
            ('http://www.linkedin.com/shareArticle?mini=true&url=', 'LinkedIn', 'fa-linkedin-square'),
        ),
    })


def search(request):
    """
    Display search results.
    """
    if not 'q' in request.GET:
        raise Http404
    q = request.GET['q']
    return render(request, 'articles/search.html', {
        'title': 'Search Results for "%s"' % q,
        'articles': Article.apply_filter(request, Q(title__icontains=q) | Q(body__icontains=q)).select_related('author', 'author__profile', 'category'),
    })


@login_required
def editor(request, id):
    """
    Display the article editor.
    """
    article = get_object_or_404(Article, pk=id) if id else None
    if article and not article.can_edit(request):
        raise Http404
    if request.method == 'POST':
        form = EditorForm(instance=article, data=request.POST)
        if form.is_valid():
            creating = article is None
            article = form.save(commit=False)
            if creating:
                article.author = request.user
            article.save()
            messages.info(request, "The article has been saved." if creating else "Your changes to the article have been saved.")
            if 'action' in request.POST and request.POST['action'] == 'continue':
                return redirect('articles:editor', article.id)
            else:
                return redirect(article)
    else:
        form = EditorForm(instance=article)
    return render(request, 'articles/editor.html', {
        'title': 'Edit "%s"' % article if article else 'New Article',
        'form': form,
        'description': "Use the form below to %s." % ('edit the article' if article else 'create an article'),
    })


def markdown(request):
    """
    Display Markdown help.
    """
    return render(request, 'articles/markdown.html', {
        'title': 'Markdown Help',
    })


@require_POST
@login_required
@transaction.atomic
def modify(request, action, id):
    """
    Attempt to modify the specified article.
    """
    article = get_object_or_404(Article, pk=id)
    if action == 'submit':
        if article.author != request.user or article.status != Article.DRAFT:
            raise Http404
        article.status = Article.UNAPPROVED
        article.save()
        template = render_to_string('articles/emails/submit.txt', {
            'article': request.build_absolute_uri(article.get_absolute_url()),
        })
        mail_admins('2buntu Article Submitted', template)
        messages.info(request, "The article has been submitted for approval by a staff member.")
    elif action == 'publish':
        if not request.user.is_staff:
            raise Http404
        article.status = Article.PUBLISHED
        article.save()
        messages.info(request, "The article has been published.")
    elif action == 'release':
        if article.author != request.user or article.cc_license:
            raise Http404
        article.cc_license = True
        article.save()
        messages.info(request, "The article is now available under a CC BY-SA 4.0 license.")
    return redirect(article)


@user_passes_test(lambda u: u.is_staff)
def schedule(request, id):
    """
    Schedule an article for publishing in the future.
    """
    article = get_object_or_404(Article, ~Q(status=Article.PUBLISHED), pk=id)
    try:
        scheduled_article = article.scheduledarticle
    except ScheduledArticle.DoesNotExist:
        scheduled_article = None
    if request.method == 'POST':
        form = ScheduledArticleForm(instance=scheduled_article, data=request.POST)
        if form.is_valid():
            scheduled_article = form.save(commit=False)
            scheduled_article.article = article
            scheduled_article.save()
            messages.info(request, "The article has been scheduled for publishing.")
            return redirect(article)
    else:
        form = ScheduledArticleForm(instance=scheduled_article)
    return render(request, 'form.html', {
        'title': 'Schedule "%s"' % article,
        'parent': {
            'title': article,
            'url': article.get_absolute_url(),
        },
        'description': "Select a date and time to publish the article.",
        'form': form,
        'action': 'Schedule',
    })


@login_required
def delete(request, id):
    """
    Delete the specified article.
    """
    article = get_object_or_404(Article, pk=id, author=request.user, status=Article.DRAFT)
    if request.method == 'POST':
        form = DeleteArticleForm(data=request.POST)
        if form.is_valid():
            article.delete()
            messages.info(request, "The article was successfully deleted.")
            return redirect(request.user.profile)
    else:
        form = DeleteArticleForm()
    return render(request, 'form.html', {
        'title': 'Delete "%s"' % article,
        'parent': {
            'title': article,
            'url': article.get_absolute_url(),
        },
        'description': "Are you sure you want to delete this article? This action cannot easily be undone.",
        'form': form,
        'action': 'Delete',
    })

twobuntu/articles/templates/articles/editor.html
{% extends "form.html" %}
{% load static %}
{% load widget_tweaks %}

{% block form_fields %}
    <div class="row">
        <div class="col-lg-8">
            {% with form.title as field %}
                {% include "fragments/field.html" %}
            {% endwith %}
        </div>
        <div class="col-lg-4">
            {% with form.category as field %}
                {% include "fragments/field.html" %}
            {% endwith %}
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <div class="form-group{% if form.body.errors %} has-error has-feedback{% endif %}">
                {% render_field form.body class+="form-control" rows="16" %}
                {% for error in form.body.errors %}
                    <p class="help-block text-danger">
                        <strong>{{ error }}</strong>
                    </p>
                {% endfor %}
            </div>
        </div>
        <div class="col-lg-4">
            <div class="well">
                <h4>Writing an Article</h4>
                <p>
                    Articles for the 2buntu blog are written in Markdown.
                    <a href="{% url "articles:markdown" %}" target="_blank">This page</a>
                    presents an overview of Markdown syntax.
                </p>
                <p>
                    When selecting a category, be as specific as possible.
                    If your article does not suit one of the existing categories,
                    please select "miscellaneous" and we will add an appropriate category.
                </p>
                <p>
                    If you need to add an image to your article, please click the "Insert image"
                    button in the toolbar or
                    <a href="{% url "images:upload" %}" target="_blank">click here if JavaScript is disabled</a>.
                    Images are hosted on our servers.
                </p>
            </div>
        </div>
    </div>
{% endblock %}

{% block form_actions %}
    <br>
    <div>
        <button type="submit" name="action" value="save" class="btn btn-primary">
            <span class="fa fa-check"></span>
            Save
        </button>
        <button type="submit" name="action" value="continue" class="btn btn-default">
            <span class="fa fa-edit"></span>
            Save and Continue Editing
        </button>
    </div>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static "js/ace.js" %}"></script>
    <script src="{% static "js/editor.js" %}"></script>
    <script src="{% static "js/detect.js" %}"></script>
    <script>
        $(function() {
            if(!isMobile()) {
                window.editor = new Editor("{% url "images:upload" %}?js");
                $('#id_title').focus();
            }
        });
    </script>
{% endblock %}

twobuntu/articles/templates/articles/markdown.html
{% extends "base.html" %}

{% block content %}
    <h2>Markdown Help</h2>
    <p>
        Articles that are composed and written for the 2buntu blog are written in a text-formatting language
        known as "Markdown". The language is both easy to read and easy to learn. What follows is a relatively
        brief overview of Markdown syntax and some examples that demonstrate its usage.
    </p>
    <hr>
    <h4>Simple Text Formatting</h4>
    <pre>**bold** | *italic* | _also italic_</pre>
    <p>The Markdown above produces the results below when rendered:</p>
    <pre><b>bold</b> | <i>italic</i> | <i>also italic</i></pre>
    <p>You can create headings with the following syntax:</p>
    <pre># Top Level Heading
## Second Level Heading</pre>
    <p>An alternative syntax is also supported:</p>
    <pre>Heading
=======</pre>
    <hr>
    <div class="row">
        <div class="col-lg-6">
            <h4>Links to URLs</h4>
            <p>Links to other pages can be created using the syntax shown below:</p>
            <pre>[link text](http://2buntu.com)</pre>
            <p>This produces the following results:</p>
            <pre><a href="http://2buntu.com">link text</a></pre>
            <p>Bare URLs will also be automatically converted to links.</p>
        </div>
        <div class="col-lg-6">
            <h4>Images</h4>
            <p>Embedding images in posts is very simple:</p>
            <pre>![hover text](http://example.com/image.jpg)</pre>
            <p>The "hover text" is displayed when the user hovers the cursor over the image.</p>
            <div class="alert alert-info">
                <strong>Note:</strong> if you are uploading a screenshot or image that you
                have permission to use, please take advantage of the upload image button
                in the toolbar.
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-lg-6">
            <h4>Lists</h4>
            <p>
                In order to display an ordered or unordered list, prefix each item with
                the approriate bullet. For ordered lists, a period may be used after the numeral:
            </p>
            <pre>1. Item 1
    1. Subitem 1
    2. Subitem 2
2. Item 2</pre>
            <p>An unordered list is created in a nearly identical manner:</p>
            <pre>* An item
* Another item
* Yet another item</pre>
        </div>
        <div class="col-lg-6">
            <h4>Code</h4>
            <p>
                If your article contains code or commands to be entered into a terminal,
                indent the block with four spaces:
            </p>
            <pre>// Create code blocks like this one
// by indenting the code with four spaces</pre>
            <p>
                If you need to refer to a variable or identifier within a paragraph
                of normal text, use the backtick character (<code>`</code>):
            </p>
            <pre>Use `printf()` to output text.</pre>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-lg-6">
            <h4>Alerts</h4>
            <p>
                You can insert an alert by using one of the alert blocks:
            </p>
            <pre>[warning]This is a warning.[/warning]</pre>
            <p>This will result in the following block:</p>
            <div class="alert alert-warning">This is a warning.</div>
        </div>
        <div class="col-lg-6">
            <h4>Types of Alerts</h4>
            <p>There are three different types of alerts. They are listed below:</p>
            <table class="table">
                <tr>
                    <td><code>[info][/info]</code></td>
                    <td>provides supplementary information of trivial importance</td>
                </tr>
                <tr>
                    <td><code>[warning][/warning]</code></td>
                    <td>warns the reader of a potential hazard</td>
                </tr>
                <tr>
                    <td><code>[danger][/danger]</code></td>
                    <td>serves as a strong caution against doing something potentially dangerous</td>
                </tr>
            </table>
        </div>
    </div>
{% endblock %}

twobuntu/articles/templates/articles/search.html
{% extends "base.html" %}

{% block content %}
    <h2>Search Results for "{{ request.GET.q }}"</h2>
    <hr>
    {% include "articles/fragments/articles.html" %}
{% endblock %}

twobuntu/articles/templates/articles/view.html
{% extends "base.html" %}
{% load gravatar %}

{% block meta %}
    <!-- Facebook Open Graph metadata -->
    <meta property="og:title" content="{{ article }}">
    <meta property="og:type" content="article">
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <meta property="og:description" content="{{ rendered|striptags|truncatewords:40 }}">
    <meta property="article:publisher" content="https://www.facebook.com/pages/2buntucom/129981420418132">
    <meta property="article:section" content="{{ article.category }}">
    <meta property="article:published_time" content="{{ article.date|date:"c" }}">
    <!-- Twitter Summary Card metadata -->
    <meta property="twitter:card" content="summary">
    <meta property="twitter:site" content="@2buntu">
    <meta property="twitter:title" content="{{ article }}">
    <meta property="twitter:description" content="{{ rendered|striptags|truncatewords:40 }}">
    <meta property="twitter:url" content="{{ request.build_absolute_uri }}">
    {% if article.image or article.category.image %}
        <!-- An image for the article -->
        <meta property="og:image" content="{{ article.image.image.url|default:article.category.image.url }}">
        <meta property="twitter:image" content="{{ article.image.image.url|default:article.category.image.url }}">
    {% endif %}
{% endblock  %}

{% block content %}
    <div class="row">
        <div class="col-sm-8">
            {% include "articles/fragments/license.html" %}
            <h2>
                {{ article }}
            </h2>
            <hr>
            {% include "articles/fragments/author.html" %}
            <hr>
            <div class="article">
                {{ rendered }}
            </div>
            <hr>
            {% include "articles/fragments/comments.html" %}
        </div>
        <div class="col-sm-4">
            {% if can_edit %}
                <div class="alert alert-warning">
                    <p>You have permission to edit this article.</p>
                    <br>
                    <a href="{% url "articles:editor" article.id %}" class="btn btn-sm btn-primary">
                        <span class="fa fa-edit"></span>
                        Edit Article
                    </a>
                </div>
            {% endif %}
            {% if not user.is_staff and article.status == article.DRAFT %}
                <div class="alert alert-warning">
                    <p>Please click the button below when you are ready to submit your article for publishing.</p>
                    <br>
                    <form method="post" action="{% url "articles:modify" "submit" article.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-primary">
                            <span class="fa fa-check"></span>
                            Submit Article
                        </button>
                    </form>
                </div>
            {% endif %}
            {% if user.is_staff and not article.status == article.PUBLISHED or article.status == article.UNAPPROVED %}
                <div class="alert alert-warning">
                    <p>This article has not yet been approved by a staff member.</p>
                    {% if user.is_staff %}
                        <br>
                        <form method="post" action="{% url "articles:modify" "publish" article.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm btn-primary">
                                <span class="fa fa-check"></span>
                                Publish Article
                            </button>
                            {% if request.user == article.author %}
                                <a href="{% url "articles:delete" article.id %}" class="btn btn-sm btn-primary">
                                    <span class="fa fa-trash-o"></span>
                                    Delete Article
                                </a>
                            {% endif %}
                        </form>
                    {% endif %}
                </div>
            {% endif %}
            {% if user.is_staff and not article.status == article.PUBLISHED %}
                <div class="alert alert-warning">
                    <p>
                        This article can be scheduled for publishing at a later date.
                    </p>
                    <br>
                    <a href="{% url "articles:schedule" id=article.id %}" class="btn btn-sm btn-primary">
                        <span class="fa fa-calendar"></span>
                        Schedule Article
                    </a>
                </div>
            {% endif %}
            {% include "fragments/search.html" %}
            <br>
            {% include "articles/fragments/share.html" %}
            <br>
            {% include "articles/fragments/related.html" %}
            <br>
            {% include "articles/fragments/apps.html" %}
        </div>
    </div>
{% endblock %}